name: FWatchDog
main: FWatchDog\FWatchDog
version: 1.1.3
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
author: FillAmeaPixelNetWork
commands:
 hack:
  description: "FWatchDog Helper Commands"
  usage: "/hack"
  permission: FWatchDog.comands.hack
 DogInfo:
  description: "FWatchDog Helper Commands"
  usage: "doginfo"
  permission: FWatchDog.commands.hack